config/routes.rb
Rails.application.routes.draw do
  # get 'projects/new'
  # get 'projects/create'
  # get 'projects/index'

  resources :projects, only: [:index, :create, :new]

  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @selected_state = 'All'
    if params[:state].present? && params[:state] != 'All'
      @selected_state = params[:state]
      @projects = Project.where('state = ?', params[:state])
    else
      @projects = Project.all
    end
  end
  
  def new
    @project = Project.new
  end

  def create
    # Project.create(
    # name: params[:project][:name]
    # description: params[:project][:description]
    # state: params[:project][:state]
    # starts_on: params[:project][:starts_on]
    # ends_on: params[:project][:ends_on]
    # )

    project = Project.new(project_params)
    project.save

    redirect_to root_path

  end

  def project_params
    params.require(:project).permit(:name, :description, :state, :starts_on, :ends_on)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gestor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs noborde">
        <li > <%= link_to "home", root_path %> </li>
        <li > <%= link_to "Nuevo Projecto", new_project_path %> </li>
      </ul>
    </div>

  
    <%= yield %>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
  </body>
</html>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/index.html.erb
<h1 class="text-center py-2">Projectos </h1>

<div class="container">
    <form method="get">
        <%= select_tag :state, options_for_select(["All", "Proposal", "In Progress", "Finished"], @selected_state) %>
        <input type="submit" value="Buscar">
    <table class="table">
        <tr>
            <td>Nombre</td>
            <td>Descripcion</td>
            <td>Estado</td>
            <td>Fecha inicio</td>
            <td>Fecha Termino</td>
        </tr>
        <% @projects.each do |project| %>
        <tr>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= project.state %></td>
            <td><%= project.starts_on %></td>
            <td><%= project.ends_on %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/projects/new.html.erb
<h1 class="text-center">Nuevo Proyecto</h1>

<div class="container">
    <%= form_with(model: @project, local: true) do |form| %>
        <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>
        <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description %>
        </div>
        <div class="form-group">
            <%= form.label :starts_on %>
            <%= form.date_field :starts_on %>
        </div>
        <div class="form-group">
            <%= form.label :ends_on %>
            <%= form.date_field :ends_on %>
        </div>
        <div class="form-group">
            <%= form.label :state %>
            <%= form.select :state, ["Proposal", "In Progress", "Finished"] %>
        </div>
        <%= form.submit %>
    <% end %>
</div>